ci: sync etcd config from APISIX (#352)
* ci: sync etcd config from APISIX

Co-authored-by: soulbird <zhaothree@gmail.com>

diff --git a/.github/workflows/apisix-docker-test.yaml b/.github/workflows/apisix-docker-test.yaml
--- a/.github/workflows/apisix-docker-test.yaml
+++ b/.github/workflows/apisix-docker-test.yaml
@@ -27,13 +27,13 @@ jobs:
       - name: Build and run
         run: |
           make build-on-${{ matrix.platform }}
-          docker-compose -f ./compose/docker-compose.yaml up -d
+          docker-compose -f ./compose/docker-compose-release.yaml up -d
           sleep 30
           docker logs compose_apisix_1
 
       - name: Test
         run: |
-          grep -C 3 '\[error\]' example/apisix_log/error.log && exit 1
+          grep -C 3 '\[error\]' compose/apisix_log/error.log && exit 1
 
           curl http://127.0.0.1:9080/apisix/admin/routes/1 \
           -H 'X-API-KEY: edd1c9f034335f136f87ad84b625c8f1' -X PUT -d '
